Repository CliMA/ClimaCore.jl, pull requests merged in 2021-11, with the labels that each got.

#267 Add unit tests for operators on the sphere
  test/runtests.jl
  test/sphere_curl.jl
  test/sphere_divergence.jl
  test/sphere_gradient.jl
  test/sphere_hyperdiffusion.jl
Labels: tests

#277 add GlobalGeometry object for converting to Cartesian
  docs/tutorials/introduction.jl
  examples/sphere/solidbody.jl
  lib/ClimaCoreVTK/src/ClimaCoreVTK.jl
  lib/ClimaCoreVTK/test/Project.toml
  lib/ClimaCoreVTK/test/runtests.jl
  src/Fields/broadcast.jl
  src/Geometry/Geometry.jl
  src/Geometry/coordinates.jl
  src/Geometry/globalgeometry.jl
  src/Operators/Operators.jl
  src/Spaces/finitedifference.jl
  src/Spaces/hybrid.jl
  src/Spaces/spectralelement.jl
  test/geometry.jl
  test/grid2d_cs.jl
  test/hybrid3d.jl
Labels: vectors, visualization, ClimaCoreVTK

#280 Shallow-water Test Case 3: Steady State Geostrophic Flow with Compact Support
  .buildkite/pipeline.yml
  examples/sphere/Project.toml
  examples/sphere/shallow_water.jl
Labels: testcase, examples, in-review

#289 Add Biased operators
  src/Operators/finitedifference.jl
  test/fdspaces.jl
Labels: enhancement

#296 allow using scalars and arrays in FieldVectors
  src/Fields/fieldvector.jl
  test/field.jl
Labels: enhancement

#299 cleanup datalayouts and make inbounds use consistent
  .buildkite/pipeline.yml
  .github/workflows/Linux-UnitTests.yml
  .github/workflows/OS-UnitTests.yml
  src/DataLayouts/DataLayouts.jl
  src/DataLayouts/struct.jl
  test/data1d.jl
Labels: refactor, performance

#300 boundscheck / eliding boundscheck consistency
  src/DataLayouts/DataLayouts.jl
  src/DataLayouts/broadcast.jl
  src/DataLayouts/struct.jl
  test/data1d.jl
  test/data1dx.jl
  test/data2d.jl
  test/data2dx.jl
Labels: refactor, performance

#292 Shallow-water Test Case: Barotropic Instability
  .buildkite/pipeline.yml
  examples/sphere/shallow_water.jl
Labels: testcase, horizontal model, examples

#302 Add JET opt tests for FD Stencil operators
  src/DataLayouts/DataLayouts.jl
  src/DataLayouts/broadcast.jl
  src/Geometry/conversions.jl
  src/Operators/Operators.jl
  src/Operators/finitedifference.jl
  src/RecursiveApply/RecursiveApply.jl
  src/interface.jl
  test/fdspaces.jl
  test/fdspaces_opt.jl
  test/runtests.jl
Labels: refactor, performance

#304 Get FD operators with AxisTensors passing JET
  src/DataLayouts/DataLayouts.jl
  src/DataLayouts/struct.jl
  src/Fields/broadcast.jl
  src/Operators/finitedifference.jl
  test/fdspaces_opt.jl
Labels: refactor, performance

#308 use slab_args, column_args in Field broadcasting machinery
  src/Fields/Fields.jl
  src/Fields/broadcast.jl
Labels: performance

#297 Allow basetype replacement
  src/DataLayouts/DataLayouts.jl
  src/DataLayouts/broadcast.jl
  src/DataLayouts/cuda.jl
  src/DataLayouts/struct.jl
  src/Fields/Fields.jl
  src/Fields/fieldvector.jl
  test/axistensors.jl
  test/data2d.jl
  test/field.jl
Labels: bug, enhancement

#288 Conformal cubed sphere support and add warp/unwarp function tests
  Project.toml
  src/Meshes/Meshes.jl
  src/Meshes/warp_cube_to_sphere.jl
  test/Project.toml
  test/cubed_spheres.jl
  test/runtests.jl
  test/sphere_geometry.jl
Labels: enhancement, horizontal model, feature, in-review

#311 Spectral space JET optimization tests
  Project.toml
  src/Geometry/conversions.jl
  src/Operators/spectralelement.jl
  src/Spaces/dss.jl
  src/Spaces/quadrature.jl
  src/Topologies/grid2d.jl
  test/runtests.jl
  test/spectralspaces_opt.jl
Labels: refactor, performance
