Repository CliMA/ClimaCore.jl, pull requests merged in 2021-09, with the labels that each got.

#150 fix typo in 1d spectral space metric
  src/Spaces/spectralelement.jl
  test/spaces.jl
Labels: bug, needs test

#156 Add an additional diagonal hybrid domain test
  test/hybrid.jl
Labels: testcase

#161 Fix sgeom⁺ in SpectralElementSpace2D
  src/Spaces/spectralelement.jl
Labels: bug

#162 Add a more compact show method for DataLayouts
  src/DataLayouts/DataLayouts.jl
Labels: enhancement

#159 add transform function
  examples/column/hydrostatic_ekman.jl
  src/Geometry/axistensors.jl
  src/Geometry/conversions.jl
  src/Operators/finitedifference.jl
  test/axistensors.jl
Labels: vectors

#146 Add cube surface mesh.
  Project.toml
  examples/bickleyjet/bickleyjet_cg_unsmesh.jl
  src/Domains/Domains.jl
  src/Meshes/BoxMesh.jl
  src/Meshes/CubedSphereMesh.jl
  src/Meshes/Meshes.jl
  src/Topologies/Topologies.jl
  src/Topologies/grid2d.jl
  test/Project.toml
  test/grid2d.jl
  test/grid2d_cs.jl
  test/runtests.jl
Labels: Unstructured 2D mesh

#176 Document finite difference stencils
  docs/make.jl
  docs/src/operators.md
  src/Operators/finitedifference.jl
  test/fdspaces.jl
Labels: documentation

#144 Customized tridiagonal solver
  examples/column/hydrostatic_implicit.jl
Labels: enhancement

#193 Convergence tests for FD operators in 1D
  test/fdspaces.jl
Labels: tests

#197 More work on 1D FD space convergence tests
  test/fdspaces.jl
Labels: tests

#198 Fix call to coordinates_data
  src/Spaces/finitedifference.jl
Labels: bugfix :bug:

#205 Embedded domain field into unstructured 2D mesh struct.
  .buildkite/pipeline.yml
  examples/bickleyjet/bickleyjet_cg_unsmesh.jl
  src/Domains/Domains.jl
  src/Meshes/Meshes.jl
  src/Meshes/box_mesh.jl
  src/Meshes/sphere_mesh.jl
  src/Meshes/warp_cube_to_sphere.jl
  src/Topologies/Topologies.jl
  src/Topologies/grid2d.jl
  test/grid2d.jl
  test/grid2d_cs.jl
Labels: Unstructured 2D mesh
