Repository CliMA/ClimaCore.jl, pull requests merged in 2021-12, with the labels that each got.

#317 fix upper boundscheck on VF (column) datalayout
  src/DataLayouts/DataLayouts.jl
Labels: bug

#324 slightly re-work scalar asignment for fields, datalayout
  src/DataLayouts/broadcast.jl
  src/Fields/broadcast.jl
  test/field.jl
Labels: enhancement

#328 Switch (warped) slice models plot output to use triplots
  Project.toml
  src/Plots/plots.jl
Labels: enhancement

#329 README: Add Zenodo's DOI badge
  README.md
Labels: documentation

#330 fix visual artifact in interpolated slice plots with topo
  src/Operators/spectralelement.jl
  src/Plots/plots.jl
Labels: bug

#342 force optimization of column() to reduce allocations in complex stencil codes
  src/Geometry/conversions.jl
  src/Operators/finitedifference.jl
  test/fdspaces_opt_examples.jl
Labels: bug, performance

#347 Add more fd operator tests
  test/fdspaces_opt_examples.jl
Labels: tests

#350 Add ntuple field perf tests
  test/fdspaces_opt_examples.jl
Labels: performance

#313 unit tests and convergence tests for vector diffusion and hyperdiffusion
  test/sphere_diffusion_vec.jl
  test/sphere_hyperdiffusion_vec.jl
  test/sphere_sphericalharmonics.jl
Labels: tests

#340 README: Update project info and technical aims/support
  README.md
Labels: documentation

#345 ClimaCoreVTK writevtk for NamedTuples of time series fields
  lib/ClimaCoreVTK/src/ClimaCoreVTK.jl
  lib/ClimaCoreVTK/test/runtests.jl
Labels: enhancement, API, ClimaCoreVTK, in-review

#377 Fix product metric terms
  src/Spaces/hybrid.jl
  test/hybrid3d.jl
Labels: bug

#381 add extruded cubed sphere level plot
  src/Fields/Fields.jl
  src/Plots/plots.jl
Labels: enhancement, visualization

#358 Add the 3d deformation flow test case
  .buildkite/pipeline.yml
  examples/3dsphere/Project.toml
  examples/3dsphere/deformation_flow.jl
Labels: testcase

#385 add the baroclinic wave test case
  .buildkite/pipeline.yml
  examples/3dsphere/baroclinic_wave.jl
Labels: testcase, Work-in-progress
