Repository CliMA/ClimaCore.jl, pull requests merged in 2022-07, with the labels that each got.

#785 Add and fix Aqua tests
  src/DataLayouts/broadcast.jl
  src/Fields/field_iterator.jl
  src/Geometry/axistensors.jl
  src/Operators/stencilcoefs.jl
  src/Spaces/Spaces.jl
  src/Spaces/dss.jl
  test/Project.toml
  test/aqua.jl
  test/runtests.jl
Labels: performance, tests

#797 Optimize compose pointwise stencils
  perf/Manifest.toml
  perf/Project.toml
  src/Operators/pointwisestencil.jl
  test/Operators/finitedifference/wfact.jl
  test/runtests.jl
Labels: performance

#799 Add JET test for apply in linsolve kernel
  test/Operators/finitedifference/linsolve.jl
  test/Operators/finitedifference/wfact.jl
  test/runtests.jl
Labels: performance, tests

#800 Bump patch version for new release
  Project.toml
  benchmarks/bickleyjet/Project.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/Manifest.toml
  examples/Project.toml
  lib/ClimaCorePlots/test/Project.toml
  perf/Manifest.toml
Labels: Release

#804 Downgrade plots and pin version
  .dev/up_deps.jl
  docs/Manifest.toml
  examples/Manifest.toml
Labels: Dependencies

#810 Remove develop for perf env
  .buildkite/pipeline.yml
Labels: CI

#762 HDF5 reader/writer
  Project.toml
  docs/Manifest.toml
  docs/src/api.md
  examples/Manifest.toml
  perf/Manifest.toml
  src/ClimaCore.jl
  src/InputOutput/InputOutput.jl
  src/InputOutput/readers.jl
  src/InputOutput/writers.jl
  test/InputOutput/hybrid2dbox.jl
  test/InputOutput/hybrid2dbox_stretched.jl
  test/InputOutput/hybrid3dbox.jl
  test/InputOutput/hybrid3dcubedsphere.jl
  test/InputOutput/runtests_inputoutput.jl
  test/InputOutput/spectralelement2d.jl
  test/runtests.jl
Labels: IO

#809 Use 3rd-order upwinding in HS
  examples/hybrid/sphere/held_suarez_rhoe.jl
Labels: vertical model

#814 Remove `LOAD_PATH` from perf env
  perf/Manifest.toml
  perf/Project.toml
  perf/allocs.jl
  perf/allocs_per_case.jl
  perf/benchmark.jl
  perf/flame.jl
Labels: CI

#820 Use SafeTestsets in test suite
  test/DataLayouts/data1dx.jl
  test/Geometry/axistensors.jl
  test/Meshes/rectangle.jl
  test/Operators/hybrid/2d.jl
  test/Operators/hybrid/3d.jl
  test/Project.toml
  test/Spaces/sphere.jl
  test/runtests.jl
Labels: tests

#823 Add column benchmarks
  .buildkite/pipeline.yml
  test/Operators/finitedifference/column_benchmark.jl
  test/Operators/finitedifference/column_benchmark_kernels.jl
  test/Operators/finitedifference/column_benchmark_profile.jl
  test/Operators/finitedifference/column_benchmark_utils.jl
  test/Project.toml
Labels: tests, Performance monitoring :mag::rocket:

#824 Correct broken tests
  test/Operators/finitedifference/column_benchmark_utils.jl
Labels: tests, Performance monitoring :mag::rocket:

#825 Widen column benchmarks
  test/Operators/finitedifference/column_benchmark_utils.jl
Labels: tests, Performance monitoring :mag::rocket:

#828 Widen column benchmark tests
  test/Operators/finitedifference/column_benchmark_kernels.jl
  test/Operators/finitedifference/column_benchmark_profile.jl
  test/Operators/finitedifference/column_benchmark_utils.jl
Labels: tests, Performance monitoring :mag::rocket:

#832 Expand column perf tests to include hspaces
  test/Operators/finitedifference/column_benchmark.jl
  test/Operators/finitedifference/column_benchmark_utils.jl
Labels: tests, Performance monitoring :mag::rocket:

#829 Improve performance of column operators
  .github/workflows/OS-UnitTests.yml
  src/DataLayouts/DataLayouts.jl
  src/DataLayouts/broadcast.jl
  src/DataLayouts/struct.jl
  src/Fields/Fields.jl
  src/Fields/broadcast.jl
  src/Fields/indices.jl
  src/Geometry/axistensors.jl
  src/Geometry/conversions.jl
  src/Geometry/coordinates.jl
  src/Geometry/localgeometry.jl
  src/Operators/finitedifference.jl
  src/RecursiveApply/RecursiveApply.jl
  src/Spaces/hybrid.jl
  src/Spaces/spectralelement.jl
  test/Operators/finitedifference/column_benchmark.jl
  test/Operators/finitedifference/column_benchmark_kernels.jl
  test/Operators/finitedifference/column_benchmark_profile.jl
  test/Operators/finitedifference/column_benchmark_utils.jl
  test/Operators/finitedifference/opt.jl
  test/Operators/hybrid/dss_opt.jl
  test/Operators/hybrid/opt.jl
  test/runtests.jl
Labels: performance

#830 precompute inverse Jacobian
  src/Geometry/localgeometry.jl
  src/Operators/finitedifference.jl
  src/Operators/operator2stencil.jl
  src/Operators/spectralelement.jl
  test/Fields/field.jl
Labels: performance

#836 Bump patch version for new release
  .buildkite/pipeline.yml
  Project.toml
  perf/Project.toml
  test/runtests.jl
Labels: Release, Dependencies

#834 use project instead of transform to access contravariant components
  src/Geometry/conversions.jl
Labels: performance

#841 Fix AxisTensor show
  src/Geometry/axistensors.jl
  test/Geometry/axistensors.jl
Labels: Logging :ledger:

#840 Split implicit operator tests to reduce ci times
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  test/Operators/finitedifference/implicit_stencils.jl
  test/Project.toml
Labels: Continuous integration :gear:

#842 Add axis tensor tests
  .buildkite/pipeline.yml
  src/Geometry/axistensors.jl
  test/Geometry/axistensor_conversion_benchmarks.jl
  test/Geometry/transform_project.jl
  test/Geometry/used_project_args.jl
  test/Geometry/used_transform_args.jl
Labels: Performance monitoring :mag::rocket:

#847 Cache contravariant metric tensor
  src/Geometry/localgeometry.jl
  test/Fields/field.jl
Labels: performance
