Repository CliMA/ClimaCore.jl, pull requests merged in 2022-04, with the labels that each got.

#628 Add column plots
  examples/hybrid/sphere/held_suarez_rhotheta.jl
  src/Fields/field_iterator.jl
Labels: visualization

#661 Fix test env OrdinaryDiffEq to fix CI
  test/Project.toml
Labels: CI

#660 Plane lim use time history
  examples/Manifest.toml
  examples/plane/limiters_advection.jl
Labels: examples, limiters

#657 Define set! on fields
  docs/src/api.md
  src/Fields/Fields.jl
  test/Fields/field.jl
Labels: enhancement

#643 High-order BCs for Upwind 3rd-Order composite operator
  src/Operators/finitedifference.jl
  test/Operators/finitedifference/column.jl
Labels: vertical model, boundary conditions

#683 Fix ThirdOrderOneSided stencil right boundary assert
  src/Operators/finitedifference.jl
Labels: bug, bugfix

#614 Sb/online sphere remap
  docs/src/lib/ClimaCoreTempestRemap.md
  lib/ClimaCoreTempestRemap/src/ClimaCoreTempestRemap.jl
  lib/ClimaCoreTempestRemap/src/onlineremap.jl
  lib/ClimaCoreTempestRemap/test/online_remap.jl
  lib/ClimaCoreTempestRemap/test/runtests.jl
  src/Spaces/spectralelement.jl
Labels: feature, ClimaCoreTempestRemap

#682 add docs for finite difference operator internals
  docs/src/operators.md
  src/Operators/finitedifference.jl
Labels: documentation, vertical model

#672 Add scaling test
  .buildkite/scaling/README.md
  .buildkite/scaling/pipeline.yml
  examples/hybrid/driver.jl
  examples/hybrid/sphere/held_suarez_rhotheta_scaling.jl
Labels: Performance monitoring

#674 Plane limiters example: reverse flow
  examples/plane/limiters_advection.jl
Labels: testcase, examples, limiters

#689 Specializing DSS versions
  .buildkite/pipeline.yml
  .github/workflows/Linux-UnitTests.yml
  .github/workflows/OS-UnitTests.yml
  examples/plane/limiters_advection.jl
  src/Fields/Fields.jl
  src/Spaces/dss.jl
  test/Project.toml
  test/runtests.jl
Labels: performance
