Repository CliMA/ClimaCore.jl, pull requests merged in 2022-12, with the labels that each got.

#1040 Upgrade to Julia 1.8.3
  .buildkite/dss_scaling/pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scaling/pipeline.yml
  docs/Manifest.toml
  examples/Manifest.toml
  examples/hybrid/sphere/README.md
  perf/Manifest.toml
Labels: Dependencies

#1053 force nsys job to run on 1 process
  .buildkite/pipeline.yml
Labels: CI

#1052 print output on error in TempestRemap
  lib/ClimaCoreTempestRemap/src/wrappers.jl
Labels: ClimaCoreTempestRemap

#1042 Update ClimaCoreTempestRemap compat entries
  docs/Manifest.toml
  examples/Manifest.toml
  lib/ClimaCoreTempestRemap/Project.toml
  lib/ClimaCoreTempestRemap/src/exodus.jl
  perf/Manifest.toml
Labels: ClimaCoreTempestRemap

#1055 ClimaCoreTempestRemap: add compat for ClimaComms
  lib/ClimaCoreTempestRemap/Project.toml
Labels: ClimaCoreTempestRemap

#1033 Valeria/bubble correction
  docs/src/api.md
  examples/sphere/limiters_advection.jl
  src/Spaces/spectralelement.jl
  test/Spaces/sphere.jl
Labels: enhancement, horizontal model, feature

#1060 Bump ClimaCore to v0.10.22
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Release

#1035 Docs: some improvements
  docs/make.jl
  docs/src/Contributing.md
  docs/src/api.md
  docs/src/assets/cubedsphere_spacefillingcurve.png
  docs/src/code_of_conduct.md
  docs/src/cubedsphere_spacefillingcurve.png
  docs/src/index.md
  docs/src/installation_instructions.md
  docs/src/lib/ClimaCoreMakie.md
  docs/src/lib/ClimaCorePlots.md
  docs/src/lib/ClimaCoreSpectra.md
  docs/src/lib/ClimaCoreTempestRemap.md
  lib/ClimaCoreTempestRemap/src/onlineremap.jl
  src/Meshes/Meshes.jl
  src/Topologies/Topologies.jl
Labels: documentation

#1061 Remove one job in allocs table
  perf/allocs.jl
Labels: Performance monitoring :mag::rocket:, Allocations

#1065 Add and fix broken allocation test
  Project.toml
  src/Fields/fieldvector.jl
  test/Fields/field_opt.jl
Labels: Inference, Allocations

#1066 Update manifest files
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies
