Repository CliMA/ClimaCore.jl, pull requests merged in 2022-11, with the labels that each got.

#1005 Bump patch version
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Release, Dependencies

#1007 Add Base(-) for 1D X,Y,Z Points
  src/Geometry/coordinates.jl
  src/Meshes/interval.jl
  test/Geometry/geometry.jl
Labels: enhancement, API, feature

#999 Improve show invalidations
  src/Fields/Fields.jl
  test/Fields/field.jl
Labels: Latency

#1009 Bump patch version, upgrade deps
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Release
