Repository CliMA/ClimaCore.jl, pull requests merged in 2022-03, with the labels that each got.

#565 Add missing existing Interpolation operators to docs
  docs/src/operators.md
Labels: documentation

#564 Add broken allocation tests for implicit fd stencils
  test/Operators/finitedifference/implicit_stencils.jl
  test/Operators/finitedifference/opt_implicit_stencils.jl
  test/runtests.jl
Labels: Performance monitoring

#567 ClimaCoreVTK: writevtk for latlong time series
  lib/ClimaCoreVTK/test/runtests.jl
Labels: tests, ClimaCoreVTK

#572 Upwind3rdOrderBiasedProductC2F
  docs/refs.bib
  docs/src/operators.md
  src/Operators/finitedifference.jl
  test/Operators/finitedifference/column.jl
Labels: enhancement, vertical model, API, in-review

#573 Get rid of find statements in the core DSS kernel.
  examples/bickleyjet/bickleyjet_cg_invariant_hypervisc.jl
  src/Spaces/dss.jl
  src/Topologies/dtopology2d.jl
  test/Project.toml
  test/Topologies/dtopo4.jl
Labels: in-review, distributed

#599 merge weighted_dss! function
  examples/bickleyjet/bickleyjet_cg_invariant_hypervisc.jl
  examples/hybrid/bubble3d_invariant_totalenergy.jl
  src/Spaces/dss.jl
Labels: in-review, distributed

#608 ClimaCoreMakie: Always use GLMakie in unit tests
  lib/ClimaCoreMakie/test/runtests.jl
Labels: tests, ClimaCoreMakie

#617 ClimaCoreVTK doc: can only be one default
  lib/ClimaCoreVTK/src/ClimaCoreVTK.jl
Labels: documentation

#616 ClimaCorePlots: add 3D extruded sphere unit tests
  lib/ClimaCorePlots/test/runtests.jl
Labels: tests, ClimaCorePlots

#637 Fix hyperdiffusion+diffusion formula in bubble_2d_rhotheta.jl
  examples/hybrid/plane/bubble_2d_rhotheta.jl
Labels: bugfix

#634 Add performance writeup to ClimaCore
  docs/make.jl
  docs/src/performance_tips.md
Labels: documentation
