Repository CliMA/ClimaCore.jl, pull requests merged in 2022-10, with the labels that each got.

#961 Add Aqua ambiguities test
  src/Geometry/axistensors.jl
  src/Operators/finitedifference.jl
  src/Operators/stencilcoefs.jl
  src/RecursiveApply/RecursiveApply.jl
  test/aqua.jl
Labels: tests, Latency

#975 Fix some tests, try to fix broken tests
  test/Fields/field.jl
  test/Fields/field_opt.jl
  test/Fields/util_spaces.jl
Labels: tests

#977 Add `number_of_columns` for computing number of columns
  examples/hybrid/sphere/held_suarez_rhotheta.jl
  examples/hybrid/sphere/held_suarez_rhotheta_scaling.jl
  src/Fields/indices.jl
  test/Fields/field.jl
Labels: enhancement

#978 Extend and fix Ref broadcasting with StencilCoefs
  .buildkite/pipeline.yml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  src/Operators/finitedifference.jl
  test/Fields/field_opt.jl
  test/Operators/finitedifference/opt_examples.jl
Labels: performance

#973 make getindex/setindex on ScalarWrapper more specific
  .buildkite/pipeline.yml
  src/Fields/fieldvector.jl
Labels: Latency

#984 Add broken allocation tests for broadcasting with FieldVectors
  test/Fields/field_opt.jl
Labels: tests, Allocations

#985 Fix FieldVector broadcast allocations
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  src/Fields/fieldvector.jl
  test/Fields/field_opt.jl
Labels: Allocations

#979 lib/ClimaCoreSpectra
  .github/workflows/ClimaCoreSpectra.yml
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/refs.bib
  docs/src/lib/ClimaCoreSpectra.md
  lib/ClimaCoreSpectra/LICENSE
  lib/ClimaCoreSpectra/Project.toml
  lib/ClimaCoreSpectra/examples/Project.toml
  lib/ClimaCoreSpectra/examples/gcm_remap_and_spectra.jl
  lib/ClimaCoreSpectra/src/ClimaCoreSpectra.jl
  lib/ClimaCoreSpectra/src/gcm_spectra.jl
  lib/ClimaCoreSpectra/test/Project.toml
  lib/ClimaCoreSpectra/test/gcm_visual_test.jl
  lib/ClimaCoreSpectra/test/runtests.jl
  lib/ClimaCoreSpectra/test/spherical_helper.jl
  lib/README.md
Labels: enhancement, visualization, feature

#992 CI: add memory in buildkite job
  .buildkite/pipeline.yml
Labels: CI

#993 Expand dz_field tests, add more coords support
  Project.toml
  docs/src/api.md
  src/Fields/Fields.jl
  src/Geometry/axistensors.jl
  src/Operators/integrals.jl
  src/Spaces/finitedifference.jl
  test/Fields/field.jl
Labels: tests, feature

#965 Optimize halo exchange.
  .buildkite/dss_scaling/pipeline.yml
  docs/src/api.md
  examples/hybrid/hybrid3dcs_dss.jl
  examples/plot_dss_timing_results.jl
  examples/sphere/shallow_water_dss.jl
  src/Fields/Fields.jl
  src/Spaces/Spaces.jl
  src/Spaces/dss2.jl
  src/Spaces/spectralelement.jl
  src/Topologies/dtopology2d.jl
  test/Operators/spectralelement/sphere_geometry_distributed.jl
  test/Spaces/distributed/ddss2.jl
  test/Spaces/distributed/ddss3.jl
  test/Spaces/distributed/ddss4.jl
Labels: performance

#968 Add invalidations script
  .buildkite/pipeline.yml
  perf/Project.toml
  perf/invalidations.jl
Labels: Latency

#1001 Reverse stretched mesh for land model
  .buildkite/pipeline.yml
  docs/src/api.md
  src/Meshes/interval.jl
  test/Meshes/interval.jl
Labels: enhancement, API, feature

#1004 Add truncated interval mesh utility
  docs/src/api.md
  src/Meshes/Meshes.jl
  src/Meshes/interval.jl
  test/Meshes/interval.jl
Labels: enhancement, vertical model, feature
