Repository CliMA/ClimaCore.jl, pull requests merged in 2022-09, with the labels that each got.

#932 Add lim+FCT run to deformation flow example
  examples/hybrid/sphere/deformation_flow.jl
Labels: testcase, limiters, upwinding

#934 Add DSS profiling
  .buildkite/dss_scaling/pipeline.yml
  examples/hybrid/hybrid3dcs_dss.jl
  examples/plot_dss_timing_results.jl
  examples/sphere/shallow_water_dss.jl
Labels: Work-in-progress, Performance monitoring :mag::rocket:

#937 Use Space-Filling-Curve for DSS benchmarking.
  examples/hybrid/hybrid3dcs_dss.jl
  examples/sphere/shallow_water_dss.jl
Labels: Performance monitoring :mag::rocket:

#945 Inline `copyto!` to fix Ref allocations
  .buildkite/pipeline.yml
  src/DataLayouts/broadcast.jl
  src/Fields/broadcast.jl
  test/Fields/field_bc.jl
Labels: performance

#947 Bump patch version for new release
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Release

#942 Monitor cell-centered variables for dss pipeline.
  .buildkite/dss_scaling/pipeline.yml
  examples/hybrid/hybrid3dcs_dss.jl
  examples/plot_dss_timing_results.jl
  examples/sphere/shallow_water_dss.jl
Labels: Performance monitoring :mag::rocket:

#950 Add broken allocation test
  .buildkite/pipeline.yml
  test/Fields/field_opt.jl
Labels: tests

#958 Add TempestRemap Nq=5 monotone test
  lib/ClimaCoreTempestRemap/test/netcdf.jl
Labels: testcase, tests

#959 Add and fix broken tests for domain-point broadcasting
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  src/Fields/Fields.jl
  src/Fields/broadcast.jl
  test/Fields/field.jl
Labels: tests

#964 Add broken allocation test with StencilCoefs broadcasting
  test/Fields/field_opt.jl
Labels: performance
