Repository CliMA/ClimaCore.jl, pull requests merged in 2022-08, with the labels that each got.

#833 IGW: generalize example w/ non-uniform grids and update hydrostatic balance computation
  .buildkite/pipeline.yml
  examples/common_spaces.jl
  examples/hybrid/driver.jl
  examples/hybrid/plane/inertial_gravity_wave.jl
  examples/hybrid/sphere/baroclinic_wave_utilities.jl
  src/Meshes/interval.jl
Labels: vertical model, testcase, examples, upwinding

#848 Generalize axis tensor tests
  test/Geometry/axistensor_conversion_benchmarks.jl
  test/Geometry/ref_funcs.jl
  test/Geometry/transform_project.jl
Labels: Performance monitoring :mag::rocket:

#855 Improve axis tensor tests
  test/Geometry/axistensor_conversion_benchmarks.jl
  test/Geometry/func_args.jl
  test/Geometry/ref_funcs.jl
Labels: tests, Performance monitoring :mag::rocket:

#858 Improve axis tensor conversion tests
  src/Geometry/axistensors.jl
  test/Geometry/axistensor_conversion_benchmarks.jl
  test/Geometry/func_arg_types.jl
  test/Geometry/func_args.jl
  test/Geometry/ref_funcs.jl
  test/Geometry/transform_project.jl
  test/Geometry/used_project_args.jl
  test/Geometry/used_transform_args.jl
Labels: tests, Performance monitoring :mag::rocket:

#862 Minor tweaks to conversion test log
  test/Geometry/axistensor_conversion_benchmarks.jl
Labels: tests, Performance monitoring :mag::rocket:, Logging :ledger:

#856 Simple FCT in deformation flow example
  docs/src/examples.md
  examples/hybrid/sphere/deformation_flow.jl
Labels: enhancement, vertical model, testcase, examples, upwinding

#866 IGW: workaround XZ-space Covariant12Vector issue in `linear_solution!`
  examples/hybrid/plane/inertial_gravity_wave.jl
Labels: examples

#870 Add ref for simple FTC regression test
  examples/hybrid/sphere/deformation_flow.jl
Labels: documentation

#872 Add simple FCT unit tests
  test/Operators/finitedifference/column.jl
Labels: vertical model, upwinding, unit tests

#875 Upwind3rdOrderBiasedProductC2F and simple FCT: Add varying sign veloc…
  test/Operators/finitedifference/column.jl
Labels: vertical model, upwinding, unit tests

#874 Distribute shallow water driver.
  .buildkite/pipeline.yml
  examples/Manifest.toml
  examples/Project.toml
  examples/nvtx.jl
  examples/sphere/shallow_water.jl
  perf/Manifest.toml
  perf/Project.toml
Labels: performance, distributed

#876 Add tests to fix level for point spaces
  src/Spaces/finitedifference.jl
  test/Fields/field.jl
Labels: bugfix

#879 Simple 1D FCT advection test
  .buildkite/pipeline.yml
  examples/column/fct_advection.jl
  test/Operators/finitedifference/column.jl
  test/advection-diffusion1d.jl
Labels: vertical model, examples, upwinding

#885 Make BBFCT stencil symmetric
  examples/column/bb_fct_advection.jl
  src/Operators/finitedifference.jl
Labels: vertical model

#899 Deformation flow: add tracer mass conservation checks
  examples/hybrid/sphere/deformation_flow.jl
Labels: testcase, examples

#894 Add Hadley-like meridional circulation test case
  .buildkite/pipeline.yml
  examples/hybrid/sphere/hadley_circulation.jl
Labels: testcase, examples

#896 Docs: update ClimaCoreTempestRemap Example
  docs/src/lib/ClimaCoreTempestRemap.md
Labels: documentation

#897 Bump patch version for new release
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
Labels: Release, Dependencies

#907 Zalesak FCT: remove dx and add it to Hadley circ test
  examples/hybrid/sphere/hadley_circulation.jl
  src/Operators/finitedifference.jl
Labels: vertical model, examples

#910 Fix Zalesak FCT docstring and add it to the Docs
  docs/refs.bib
  docs/src/operators.md
  src/Operators/finitedifference.jl
Labels: documentation

#915 FCT: Add stretched grid tests
  examples/column/bb_fct_advection.jl
  examples/column/fct_advection.jl
  examples/column/zalesak_fct_advection.jl
  examples/hybrid/sphere/hadley_circulation.jl
Labels: vertical model, tests

#922 Fix threading condition (hitting nested threading)
  src/Operators/finitedifference.jl
Labels: performance, bugfix

#917 Do inlining and inbounds more carefully
  src/DataLayouts/DataLayouts.jl
  src/DataLayouts/broadcast.jl
  src/Fields/Fields.jl
  src/Fields/broadcast.jl
  src/Fields/fieldvector.jl
  src/Fields/indices.jl
  src/Geometry/axistensors.jl
  src/Geometry/conversions.jl
  src/Geometry/coordinates.jl
  src/Operators/finitedifference.jl
  src/Operators/operator2stencil.jl
  src/Operators/pointwisestencil.jl
  src/Operators/spectralelement.jl
  src/RecursiveApply/RecursiveApply.jl
  src/Spaces/dss.jl
  src/Spaces/finitedifference.jl
  src/Spaces/hybrid.jl
  src/Spaces/spectralelement.jl
  src/interface.jl
  test/Operators/finitedifference/linsolve.jl
Labels: performance

#924 Fix bug in implicit stencil tests
  test/Operators/finitedifference/opt_implicit_stencils.jl
Labels: tests, bugfix

#928 Valeria/limiter unit tests type
  examples/hybrid/sphere/deformation_flow.jl
  test/Limiters/limiter.jl
Labels: testcase, limiters, unit tests

#929 Add option for unthreaded bycolumn
  src/Fields/Fields.jl
  src/Fields/indices.jl
Labels: Performance monitoring :mag::rocket:
