Repository CliMA/ClimaCore.jl, pull requests merged in 2022-01, with the labels that each got.

#398 test/hybrid_opt.jl: get rid of print out, change @show -> @test_opt
  test/hybrid_opt.jl
Labels: tests

#399 ClimaCoreVTK: rename test output files to avoid overwrite
  lib/ClimaCoreVTK/test/runtests.jl
Labels: tests, ClimaCoreVTK

#401 Switch buildkite to Julia 1.7.1
  .buildkite/pipeline.yml
Labels: CI

#407 Add output viz tests for vtk data & test that the generated files can be read by paraview
  .buildkite/pipeline.yml
  .github/workflows/ClimaCoreMakie.yml
  .github/workflows/ClimaCorePlots.yml
  .github/workflows/ClimaCoreVTK.yml
  lib/ClimaCoreMakie/test/runtests.jl
  lib/ClimaCorePlots/test/runtests.jl
  lib/ClimaCoreVTK/paraview/renderimage.py
  lib/ClimaCoreVTK/test/runtests.jl
Labels: enhancement, CI

#408 Add a FD perf test
  test/fdspaces_opt_examples.jl
Labels: performance, tests

#411 fix energy equations
  examples/3dsphere/baroclinic_wave.jl
  examples/3dsphere/solid_body_rotation_3d.jl
Labels: bug

#413 Add some perf scripts
  .buildkite/pipeline.yml
  examples/3dsphere/baroclinic_wave.jl
  examples/hybrid/bubble_2d.jl
  examples/hybrid/bubble_3d.jl
  examples/sphere/shallow_water.jl
  perf/Project.toml
  perf/allocs.jl
  perf/allocs_per_case.jl
Labels: Performance monitoring

#415 Time some solves, make `tuplemap` call `map`
  examples/3dsphere/baroclinic_wave.jl
  examples/hybrid/bubble_2d.jl
  examples/hybrid/bubble_3d.jl
  examples/sphere/shallow_water.jl
  src/RecursiveApply/RecursiveApply.jl
Labels: performance, Performance monitoring

#418 Track allocations for solid body rotation
  examples/3dsphere/solid_body_rotation_3d.jl
  perf/allocs.jl
Labels: Performance monitoring

#379 add the nonhydrostatic gravity wave test case
  .buildkite/pipeline.yml
  examples/3dsphere/nonhydrostatic_gravity_wave.jl
Labels: testcase, Work-in-progress

#421 Fix float type bug
  src/Geometry/coordinates.jl
Labels: bugfix

#425 Update lib READMEs
  lib/ClimaCoreMakie/README.md
  lib/ClimaCorePlots/README.md
  lib/ClimaCoreVTK/README.md
Labels: documentation, ClimaCoreVTK

#428 Use better recursion pattern
  src/Operators/spectralelement.jl
Labels: performance

#429 fix return values to align with setindex! behavior
  src/DataLayouts/struct.jl
  src/Operators/finitedifference.jl
  test/DataLayouts/data1d.jl
  test/DataLayouts/data2d.jl
Labels: bug

#412 add orth slice plots for 3D hybrid domains
  examples/hybrid/bubble3d_invariant.jl
  lib/ClimaCorePlots/src/ClimaCorePlots.jl
  lib/ClimaCorePlots/test/runtests.jl
  src/Geometry/coordinates.jl
  src/Spaces/hybrid.jl
  src/Spaces/spectralelement.jl
Labels: enhancement, visualization

#438 Hoist some getproperty calls
  examples/hybrid/bubble_2d.jl
Labels: performance

#442 Increase 2d bubble timestep, reduce io
  examples/hybrid/bubble_2d.jl
Labels: CI

#440 restrict curl / weak curl to work on only covariant vector field inputs, this enables us to optimize through the hyperdiffusion operation
  docs/tutorials/introduction.jl
  examples/3dsphere/baroclinic_wave.jl
  examples/3dsphere/nonhydrostatic_gravity_wave.jl
  examples/bickleyjet/bickleyjet_cg_invariant_hypervisc.jl
  examples/hybrid/bubble3d_invariant.jl
  examples/hybrid/bubble3d_invariant_totalenergy.jl
  examples/sphere/shallow_water.jl
  src/Geometry/conversions.jl
  src/Operators/finitedifference.jl
  src/Operators/spectralelement.jl
  src/Spaces/dss.jl
  test/spectraloperators.jl
  test/spectralspaces_opt.jl
  test/sphere_diffusion_vec.jl
  test/sphere_hyperdiffusion_vec.jl
Labels: API

#441 Use ReportMetrics.jl
  perf/Project.toml
  perf/allocs.jl
  perf/allocs_per_case.jl
Labels: CI

#446 Add neighboring_elements
  src/Topologies/Topologies.jl
  src/Topologies/interval.jl
  src/Topologies/topology2d.jl
  test/Topologies/cubedsphere.jl
  test/Topologies/rectangle.jl
Labels: enhancement, horizontal model, API, tests, Unstructured 2D mesh, in-review

#451 Monitor implicit baroclinic wave allocations
  examples/3dsphere/baroclinic_wave_rho_etot.jl
  perf/allocs.jl
Labels: Performance monitoring

#458 Fix allocation monitoring
  examples/3dsphere/baroclinic_wave.jl
  examples/3dsphere/baroclinic_wave_rho_etot.jl
  examples/3dsphere/solid_body_rotation_3d.jl
  examples/hybrid/bubble_2d.jl
  examples/hybrid/bubble_3d.jl
  examples/sphere/shallow_water.jl
  perf/allocs_per_case.jl
Labels: Performance monitoring, bugfix

#456 Add 1D field plotting.
  lib/ClimaCorePlots/Project.toml
  lib/ClimaCorePlots/src/ClimaCorePlots.jl
  lib/ClimaCorePlots/test/runtests.jl
Labels: enhancement, visualization

#459 add generalized exp stretching and interval mesh tests
  Project.toml
  src/Meshes/Meshes.jl
  src/Meshes/interval.jl
  test/Meshes/interval.jl
  test/Operators/finitedifference/column.jl
  test/runtests.jl
Labels: enhancement

#462 Preallocate some fields in implicit baroclinic wave
  examples/3dsphere/baroclinic_wave_rho_etot.jl
  examples/3dsphere/baroclinic_wave_rho_etot_utils.jl
Labels: performance

#467 Fix baroclinic wave
  examples/3dsphere/baroclinic_wave_rho_etot.jl
  examples/3dsphere/baroclinic_wave_rho_etot_utils.jl
Labels: bugfix

#457 Add latlong option to VTK output
  lib/ClimaCoreVTK/src/ClimaCoreVTK.jl
  lib/ClimaCoreVTK/test/runtests.jl
Labels: enhancement, visualization, ClimaCoreVTK

#478 Define copyto! for diagonalized field vectors
  src/Fields/fieldvector.jl
Labels: performance

#482 Use integrator interface, add flame script
  .gitignore
  examples/3dsphere/baroclinic_wave.jl
  examples/3dsphere/solid_body_rotation_3d.jl
  examples/hybrid/bubble_2d.jl
  examples/hybrid/bubble_3d.jl
  examples/sphere/shallow_water.jl
  perf/allocs_per_case.jl
  perf/flame.jl
Labels: Performance monitoring

#484 fix slab/column broadcasting
  src/DataLayouts/broadcast.jl
  src/DataLayouts/struct.jl
  src/Fields/Fields.jl
  test/DataLayouts/data2d.jl
  test/Fields/field.jl
Labels: bug, bugfix

#486 promote wrapped datastyles for field broadcasts
  src/Fields/broadcast.jl
  test/Fields/field.jl
Labels: bug, bugfix

#373 Add `DistributedTopology2D`
  .buildkite/pipeline.yml
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  src/Fields/Fields.jl
  src/Spaces/Spaces.jl
  src/Spaces/dss.jl
  src/Spaces/hybrid.jl
  src/Spaces/spectralelement.jl
  src/Topologies/Topologies.jl
  src/Topologies/dtopology2d.jl
  src/Topologies/topology2d.jl
  test/Operators/hybrid/3d.jl
  test/Project.toml
  test/Spaces/distributed.jl
  test/Spaces/distributed/ddss2.jl
  test/Spaces/distributed/ddss3.jl
  test/Spaces/distributed/ddss4.jl
  test/Spaces/distributed/ddss_setup.jl
  test/Topologies/distributed.jl
  test/Topologies/dtopo4.jl
  test/runtests.jl
Labels: performance, feature, distributed

#495 Prep examples for perf analysis
  examples/3dsphere/held_suarez_rho_etot.jl
  examples/3dsphere/solid_body_rotation_3d.jl
  examples/hybrid/bubble3d_invariant_totalenergy.jl
  perf/allocs.jl
Labels: refactor, performance, Performance monitoring
