Repository CliMA/ClimaCore.jl, pull requests merged in 2022-06, with the labels that each got.

#743 Move links to sidebar
  docs/make.jl
  docs/src/api.md
  docs/src/intro-to-sem.md
  docs/src/intro-to-vectors.md
Labels: documentation

#752 Obtain elemorder from space filling curve.
  .gitignore
  Project.toml
  docs/Manifest.toml
  docs/src/api.md
  docs/src/assets/cubedsphere_spacefillingcurve.png
  examples/Manifest.toml
  examples/Project.toml
  src/Meshes/common.jl
  src/Topologies/dtopology2d.jl
  test/Spaces/distributed/ddss_setup.jl
  test/Spaces/distributed/gather4.jl
  test/Topologies/cubedsphere_sfc.jl
  test/Topologies/dtopo4.jl
  test/Topologies/rectangle_sfc.jl
  test/runtests.jl
Labels: performance

#757 2D rising thermal bubble: increase dt and final time
  examples/hybrid/plane/bubble_2d_invariant_rhoe.jl
Labels: examples

#759 2D Rising thermal bubble: Use 3rd-order upwinding
  examples/hybrid/plane/bubble_2d_invariant_rhoe.jl
Labels: examples, upwinding

#769 Examples: Use 3rd-order-upwind in inertial gravity wave
  .buildkite/pipeline.yml
  examples/hybrid/driver.jl
  examples/hybrid/plane/inertial_gravity_wave.jl
  examples/hybrid/staggered_nonhydrostatic_model.jl
Labels: examples, upwinding

#771 Fix show for AxisTensors
  src/Geometry/axistensors.jl
  test/Geometry/axistensors.jl
Labels: bugfix

#780 Add mismatched spaces error back in
  src/Operators/finitedifference.jl
Labels: Defensive programming :crossed_swords:

#777 Fix more performance tests
  test/Operators/finitedifference/opt_implicit_stencils.jl
Labels: performance, tests

#781 Enforce tuple with uniform eltype
  src/Operators/stencilcoefs.jl
Labels: performance
