Repository CliMA/ClimaCore.jl, pull requests merged in 2022-02, with the labels that each got.

#426 Optimization-based limiters for advection/solidbody equation
  .buildkite/pipeline.yml
  docs/refs.bib
  docs/src/api.md
  examples/sphere/opt_limiters_solidbody.jl
  src/ClimaCore.jl
  src/Limiters/Limiters.jl
  src/Limiters/limiter.jl
  src/Topologies/topology2d.jl
  test/Limiters/limiter.jl
  test/runtests.jl
Labels: enhancement, API, feature, in-review

#505 Update examples/README adding quotes in include
  examples/README.md
Labels: documentation

#506 Define `deepcopy_internal` for Fields
  src/Fields/fieldvector.jl
  test/Fields/field.jl
Labels: enhancement

#507 Better `norm` docstring
  src/Fields/mapreduce.jl
Labels: documentation

#520 Add euclidean_distance support
  src/Geometry/globalgeometry.jl
  test/Geometry/geometry.jl
Labels: API, feature, in-review

#528 Fix allocations and other implicit solver improvements
  examples/3dsphere/balanced_flow_ρe.jl
  examples/3dsphere/baroclinic_wave_ρe.jl
  examples/3dsphere/held_suarez_ρe.jl
  examples/3dsphere/utilities.jl
  examples/implicit_solver_debugging_tools.jl
  examples/schur_complement_W.jl
  src/Fields/Fields.jl
  src/Fields/fieldvector.jl
  src/Fields/mapreduce.jl
Labels: performance

#532 gather fields to root
  examples/Manifest.toml
  examples/Project.toml
  examples/bickleyjet/bickleyjet_cg_invariant_hypervisc.jl
  src/DataLayouts/DataLayouts.jl
  src/Spaces/spectralelement.jl
  test/Spaces/distributed.jl
  test/Spaces/distributed/ddss4.jl
  test/Spaces/distributed/ddss_setup.jl
  test/Spaces/distributed/gather4.jl
Labels: performance, bugfix

#536 examples/Project.toml: Add ClimaCoreVTK
  examples/Manifest.toml
  examples/Project.toml
Labels: examples, ClimaCoreVTK

#533 Advection & Divergence convergence unit tests
  test/Operators/finitedifference/column.jl
  test/Operators/hybrid/2d.jl
Labels: vertical model, tests

#551 Distribute 3D hybrid simulations.
  .buildkite/pipeline.yml
  examples/Manifest.toml
  examples/Project.toml
  examples/bickleyjet/bickleyjet_cg_invariant_hypervisc.jl
  examples/hybrid/bubble2d_invariant_totalenergy.jl
  examples/hybrid/bubble3d_invariant_totalenergy.jl
  src/Spaces/dss.jl
  src/Spaces/hybrid.jl
Labels: performance, Work-in-progress, bugfix

#508 2D Spectral Element <-> Spectral Element Remapping
  docs/refs.bib
  src/Operators/remapping.jl
  test/Operators/remapping.jl
Labels: enhancement
