Repository CliMA/ClimaCore.jl, pull requests merged in 2023-06, with the labels that each got.

#1279 Add PointSpace fallback constructor, fix arr type
  src/Spaces/pointspace.jl
  test/Fields/field.jl
Labels: bugfix

#1198 Add and fix JET tests for DSS
  .buildkite/pipeline.yml
  src/Spaces/dss.jl
  test/Operators/spectralelement/benchmark_kernels.jl
  test/Operators/spectralelement/benchmark_ops.jl
  test/Operators/spectralelement/benchmark_utils.jl
Labels: performance, bugfix

#1288 Bump patch version
  .buildkite/pipeline.yml
  .dev/Manifest.toml
  Project.toml
  benchmarks/bickleyjet/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
  perf/Manifest.toml
  test/Operators/spectralelement/benchmark_utils.jl
Labels: Release

#1298 Protect dss against incorrect buffer
  src/Spaces/dss.jl
  test/Spaces/ddss1_cs.jl
Labels: Defensive programming :crossed_swords:

#1295 Add more perf dss tests
  test/Operators/spectralelement/benchmark_kernels.jl
  test/Operators/spectralelement/benchmark_ops.jl
  test/Operators/spectralelement/benchmark_utils.jl
Labels: Performance tests

#1306 Fix dss inference
  src/RecursiveApply/RecursiveApply.jl
  test/Operators/spectralelement/benchmark_ops.jl
Labels: performance

#1309 Bump patch version for new release
  .dev/Manifest.toml
  Project.toml
  benchmarks/bickleyjet/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
  perf/Manifest.toml
Labels: Release

#1334 Extend and improve RecursiveApply, fix DSS inference
  src/RecursiveApply/RecursiveApply.jl
  src/Spaces/dss.jl
  test/Operators/spectralelement/benchmark_ops.jl
  test/RecursiveApply/recursive_apply.jl
  test/aqua.jl
Labels: tests, Inference

#1337 Inline some small dss functions
  Project.toml
  src/Spaces/dss_transform.jl
Labels: performance

#1329 Add SLEVE coordinate option
  docs/refs.bib
  docs/src/api.md
  src/Hypsography/Hypsography.jl
  test/Spaces/terrain_warp.jl
Labels: documentation, enhancement, feature

#1347 Properly deprecate `enable_threading`, bump patch version
  Project.toml
  src/DataLayouts/DataLayouts.jl
  src/interface.jl
Labels: Release

#1349 Add broken test for `pow_n` issue, fix 1126
  src/Fields/broadcast.jl
  test/Fields/field.jl
Labels: tests

#1353 Modify warning in case SLEVE scale height is poorly specified, add test.
  src/Hypsography/Hypsography.jl
  test/Spaces/terrain_warp.jl
Labels: error message, unit tests
