Repository CliMA/ClimaCore.jl, pull requests merged in 2023-05, with the labels that each got.

#1213 Add inbounds to slab indices
  src/Fields/indices.jl
Labels: performance

#1215 Remove Device mod, use ClimaComms
  examples/sphere/shallow_water_cuda.jl
  src/ClimaCore.jl
  src/Device.jl
  src/Fields/Fields.jl
  src/Fields/mapreduce.jl
  src/Operators/Operators.jl
  src/Operators/spectralelement.jl
  src/Spaces/Spaces.jl
  src/Spaces/dss.jl
  src/Spaces/extruded.jl
  src/Spaces/finitedifference.jl
  src/Spaces/pointspace.jl
  src/Spaces/spectralelement.jl
  src/Topologies/Topologies.jl
  src/Topologies/interval.jl
  src/Topologies/topology2d.jl
  src/deprecated.jl
  test/Fields/reduction_cuda.jl
  test/InputOutput/spectralelement2d.jl
  test/Operators/spectralelement/rectilinear_cuda.jl
  test/Spaces/ddss1.jl
  test/Spaces/ddss1_cs.jl
  test/Spaces/distributed_cuda/ddss2.jl
  test/Spaces/distributed_cuda/ddss3.jl
  test/Spaces/distributed_cuda/ddss4.jl
  test/Spaces/distributed_cuda/ddss_ne32_cs.jl
  test/gpu/device.jl
Labels: GPU

#1219 Fix logic in Zalesak
  examples/hybrid/sphere/deformation_flow.jl
  src/Operators/finitedifference.jl
Labels: bugfix, numerics

#1214 Bump version, update dependencies
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
  lib/ClimaCoreTempestRemap/Project.toml
  perf/Manifest.toml
Labels: Release, Dependencies

#1220 Add MPI compat for CCTR
  lib/ClimaCoreTempestRemap/Project.toml
  lib/ClimaCoreTempestRemap/src/onlineremap.jl
  lib/ClimaCoreTempestRemap/test/mpi_tests/online_remap.jl
Labels: Release

#1217 Add bench test for bycol broadcast fallback
  test/Operators/finitedifference/column_benchmark.jl
  test/Operators/finitedifference/column_benchmark_kernels.jl
  test/Operators/finitedifference/column_benchmark_utils.jl
Labels: Performance monitoring :mag::rocket:

#1225 Make implicit test variables readable
  test/Operators/finitedifference/implicit_stencils.jl
Labels: Naming conventions

#1221 Test GPU reductions for extruded spaces
  src/Fields/mapreduce_cuda.jl
  test/Fields/reduction_cuda.jl
Labels: GPU

#1229 Break up implicit stencil tests for improving inference
  implicit_stencils.html
  test/Operators/finitedifference/implicit_stencils.jl
  test/Operators/finitedifference/implicit_stencils_utils.jl
Labels: tests

#1264 Speed up inertial gravity wave examples (part of #1263)
  .buildkite/pipeline.yml
  examples/hybrid/plane/inertial_gravity_wave.jl
Labels: Continuous integration :gear:

#1261 Conditionally overload Krylov.ktypeof
  Project.toml
  benchmarks/bickleyjet/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
  perf/Manifest.toml
  src/ClimaCore.jl
  src/weak_deps/Krylov.jl
Labels: Low priority
