Repository CliMA/ClimaCore.jl, pull requests merged in 2023-11, with the labels that each got.

#1528 Add Julia 1.10rc1 to GHA CI
  .github/workflows/Linux-UnitTests.yml
Labels: Continuous integration :gear:

#1531 Bump version of ClimaCoreTempestRemap
  lib/ClimaCoreTempestRemap/Project.toml
Labels: ClimaCoreTempestRemap, Dependencies

#1541 Update to NCDataset 0.13
  examples/hybrid/sphere/hadley_circulation.jl
  lib/ClimaCoreTempestRemap/test/online_remap.jl
Labels: Dependencies

#1542 Clean up hybrid plane examples directory.
  .buildkite/pipeline.yml
  examples/hybrid/plane/bubble_2d_invariant_rhotheta.jl
  examples/hybrid/plane/bubble_2d_rhotheta.jl
  examples/hybrid/plane/density_current_2dinvariant_rhotheta.jl
  examples/hybrid/plane/topo_dc_2dinvariant_rhoe.jl
  perf/flame.jl
Labels: House cleaning :broom:

#1512 Add support for GPUs in interpolate_array
  .buildkite/pipeline.yml
  src/Remapping/Remapping.jl
  src/Remapping/distributed_remapping.jl
  src/Remapping/interpolate_array.jl
  test/Remapping/distributed_remapping.jl
Labels: GPU

#1520 Add gpu implementation of `QuasiMonotoneLimiter`
  src/Limiters/quasimonotone.jl
  src/Topologies/topology2d.jl
  test/Limiters/limiter.jl
  test/Spaces/ddss1.jl
  test/Spaces/distributed/ddss2.jl
  test/Spaces/distributed/ddss3.jl
  test/Spaces/distributed/ddss4.jl
  test/Spaces/distributed_cuda/ddss2.jl
  test/Spaces/distributed_cuda/ddss3.jl
Labels: GPU

#1544 Fix FT scope for some examples
  examples/column/bb_fct_advection.jl
  examples/column/fct_advection.jl
  examples/column/zalesak_fct_advection.jl
  examples/hybrid/box/limiters_advection.jl
  lib/ClimaCoreSpectra/test/gcm_visual_test.jl
Labels: performance, examples
