Repository CliMA/ClimaCore.jl, pull requests merged in 2023-02, with the labels that each got.

#1117 extend write_exodus for any topology
  .buildkite/pipeline.yml
  lib/ClimaCoreTempestRemap/Project.toml
  lib/ClimaCoreTempestRemap/src/exodus.jl
  lib/ClimaCoreTempestRemap/test/mpi_tests/exodus.jl
Labels: distributed

#1123 Use SnoopCompile version of `report_invalidations`
  perf/Manifest.toml
  perf/Project.toml
  perf/invalidations.jl
Labels: Latency

#1127 ClimaCoreMakie support for extruded fields + topography
  docs/src/lib/ClimaCoreMakie.md
  lib/ClimaCoreMakie/Project.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
  lib/ClimaCoreMakie/examples/Project.toml
  lib/ClimaCoreMakie/src/ClimaCoreMakie.jl
  lib/ClimaCoreMakie/test/Project.toml
  lib/ClimaCoreMakie/test/runtests.jl
Labels: ClimaCoreMakie

#767 apply operators byslab, GPU operators
  .buildkite/pipeline.yml
  examples/sphere/shallow_water_cuda.jl
  src/DataLayouts/DataLayouts.jl
  src/DataLayouts/struct.jl
  src/Device.jl
  src/Fields/Fields.jl
  src/Fields/broadcast.jl
  src/Fields/indices.jl
  src/Operators/Operators.jl
  src/Operators/spectralelement.jl
  src/Spaces/Spaces.jl
  src/Spaces/extruded.jl
  src/Spaces/spectralelement.jl
  src/Topologies/Topologies.jl
  src/Topologies/interval.jl
  test/DataLayouts/data2d.jl
  test/Operators/spectralelement/rectilinear_cuda.jl
  test/runtests.jl
Labels: GPU
