Repository CliMA/ClimaCore.jl, pull requests merged in 2023-01, with the labels that each got.

#1069 Obtain device array from ClimaComms context.
  examples/Manifest.toml
  examples/Project.toml
  examples/sphere/shallow_water_cuda.jl
  src/ClimaCore.jl
  src/Device.jl
  test/gpu/device.jl
  test/runtests.jl
Labels: draft, GPU

#1072 Update backing arrays for SpectralElementSpace2D
  examples/sphere/shallow_water_cuda.jl
  src/DataLayouts/DataLayouts.jl
  src/Spaces/Spaces.jl
  src/Spaces/spectralelement.jl
Labels: GPU

#1086 Add broken allocation tests
  test/Spaces/distributed/ddss2.jl
  test/Spaces/distributed/ddss3.jl
  test/Spaces/distributed/ddss4.jl
Labels: tests, Allocations

#1087 Conservation for bubble correction
  examples/sphere/limiters_advection.jl
  src/Spaces/spectralelement.jl
Labels: enhancement, horizontal model

#1094 Bump patch versions for new releases
  Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  lib/ClimaCorePlots/Project.toml
  lib/ClimaCoreTempestRemap/Project.toml
  lib/ClimaCoreVTK/Project.toml
  perf/Manifest.toml
Labels: Dependencies

#1098 isothermal channel example
  .buildkite/pipeline.yml
  examples/hybrid/plane/isothermal_channel.jl
Labels: examples

#1099 Add broken test to track bubble robustness bug
  test/Spaces/sphere.jl
Labels: bug, CI, tests, unit tests

#1106 Bubble correction: Fix robustness
  src/Spaces/spectralelement.jl
  test/Spaces/sphere.jl
Labels: bug, enhancement, horizontal model

#1111 cuda support for dss2 (serial)
  examples/sphere/shallow_water_cuda.jl
  src/DataLayouts/DataLayouts.jl
  src/Spaces/Spaces.jl
  src/Spaces/dss2.jl
  src/Spaces/dss2_cuda.jl
  src/Spaces/dss_transform.jl
  src/Spaces/spectralelement.jl
  src/Topologies/Topologies.jl
  src/Topologies/topology2d.jl
  test/Spaces/ddss1.jl
  test/Spaces/distributed/ddss4.jl
  test/runtests.jl
Labels: Work-in-progress
