Repository CliMA/ClimaCore.jl, pull requests merged in 2023-10, with the labels that each got.

#1477 Access horizontal space consistently
  docs/src/lib/ClimaCoreTempestRemap.md
  examples/hybrid/sphere/remap_pipeline.jl
  lib/ClimaCoreVTK/src/space.jl
  src/Fields/Fields.jl
  src/Spaces/extruded.jl
  test/Operators/hybrid/2d.jl
Labels: refactor

#1473 Fix lists in docs
  docs/src/math_framework.md
  docs/src/operators.md
Labels: documentation, House cleaning :broom:

#1475 Add distributed_remapping.jl
  .buildkite/pipeline.yml
  docs/src/api.md
  src/Remapping/Remapping.jl
  src/Remapping/distributed_remapping.jl
  src/Remapping/interpolate_array.jl
  test/Remapping/distributed_remapping.jl
Labels: distributed, remapping, diagnostic

#1495 Downgrade to CUDA 4
  .dev/Manifest.toml
  Project.toml
  benchmarks/bickleyjet/Manifest.toml
  benchmarks/bickleyjet/Project.toml
  docs/Manifest.toml
  examples/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies

#1498 Tag new release
  Project.toml
  benchmarks/bickleyjet/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
  perf/Manifest.toml
Labels: Release

#1491 Update BandedMatrices
  Project.toml
  benchmarks/bickleyjet/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
Labels: Dependencies

#1497 Add support for topography in `distributed_remapping`
  src/Hypsography/Hypsography.jl
  src/Remapping/Remapping.jl
  src/Remapping/distributed_remapping.jl
  src/Remapping/interpolate_array.jl
  test/Remapping/distributed_remapping.jl
Labels: feature

#1445 Migrate CA column ops to ClimaCore
  .buildkite/pipeline.yml
  docs/src/operators.md
  src/Operators/integrals.jl
  test/Operators/integrals.jl
Labels: needs test

#1504 Add and test function-based indefinite integrals
  src/Operators/integrals.jl
  test/Operators/integrals.jl
Labels: numerics

#1516 Bump patch version
  Project.toml
  benchmarks/bickleyjet/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
  perf/Manifest.toml
Labels: Release

#1517 Add broken GPU limiters tests, and GPU dispatch mechanism
  .buildkite/pipeline.yml
  src/Limiters/quasimonotone.jl
  test/Limiters/limiter.jl
Labels: GPU

#1519 Bypass broken sum in limiters test
  test/Limiters/limiter.jl
Labels: tests, GPU

#1523 Fixes for gpu limiters test
  src/DataLayouts/cuda.jl
  src/Limiters/quasimonotone.jl
  test/Limiters/limiter.jl
Labels: tests, GPU
