Repository CliMA/ClimaCore.jl, pull requests merged in 2023-04, with the labels that each got.

#1178 Mv bubble warning outside loop
  src/Spaces/spectralelement.jl
Labels: Logging :ledger:

#1179 Inline copyto_slab
  src/Operators/spectralelement.jl
Labels: performance

#1182 Deformation flow example: add different upwinding modes
  examples/hybrid/sphere/deformation_flow.jl
Labels: examples, upwinding, numerics

#1187 Make updating axis tensor tests easier
  test/Geometry/axistensor_conversion_benchmarks.jl
  test/Geometry/method_info.jl
Labels: Workflow :gear: :ocean:

#1188 Extend spectral element benchmarks
  .buildkite/pipeline.yml
  test/Operators/spectralelement/benchmark_kernels.jl
  test/Operators/spectralelement/benchmark_ops.jl
  test/Operators/spectralelement/benchmark_times.jl
  test/Operators/spectralelement/benchmark_utils.jl
Labels: Performance monitoring :mag::rocket:
