Repository CliMA/ClimaCore.jl, pull requests merged in 2024-04, with the labels that each got.

#1661 Update dependencies
  Project.toml
  benchmarks/bickleyjet/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
  perf/Manifest.toml
  src/Fields/Fields.jl
  src/MatrixFields/MatrixFields.jl
Labels: Dependencies

#1669 Allow remapper to take multiple Fields
  .buildkite/pipeline.yml
  NEWS.md
  src/Remapping/distributed_remapping.jl
  test/Remapping/distributed_remapping.jl
Labels: breaking :boom:

#1663 Define and use `auto_launch!`
  ext/ClimaCoreCUDAExt.jl
  ext/cuda/cuda_utils.jl
  ext/cuda/data_layouts.jl
  ext/cuda/limiters.jl
  ext/cuda/matrix_fields_multiple_field_solve.jl
  ext/cuda/operators_finite_difference.jl
  ext/cuda/operators_integral.jl
  ext/cuda/operators_spectral_element.jl
  ext/cuda/operators_thomas_algorithm.jl
  ext/cuda/remapping_distributed.jl
  ext/cuda/remapping_interpolate_array.jl
  ext/cuda/topologies_dss.jl
  test/DataLayouts/cuda.jl
Labels: performance
