Repository CliMA/ClimaCore.jl, pull requests merged in 2024-02, with the labels that each got.

#1607 Avoid StepRange in GPU kernel
  src/Operators/thomas_algorithm.jl
Labels: performance

#1608 Avoid StepRange in band_matrix_solve
  src/MatrixFields/single_field_solver.jl
Labels: performance

#1617 Fix inference errors when not debugging
  src/MatrixFields/field_matrix_iterative_solver.jl
  test/MatrixFields/field_matrix_solvers.jl
Labels: Inference

#1623 Do not test field mat solvers logs on gpu
  test/MatrixFields/field_matrix_solvers.jl
Labels: CI

#1610 Rewrite non-conservative interpolation
  Project.toml
  benchmarks/bickleyjet/Manifest.toml
  docs/Manifest.toml
  examples/Manifest.toml
  perf/Manifest.toml
  src/Quadratures/Quadratures.jl
  src/Remapping/Remapping.jl
  src/Remapping/distributed_remapping.jl
  src/Remapping/interpolate_array.jl
  src/Remapping/remapping_utils.jl
  test/Remapping/distributed_remapping.jl
  test/runtests.jl
Labels: refactor, performance, distributed, remapping, diagnostic, GPU, software, breaking :boom:

#1016 Add broken alloc tests for assigning SArrays and tuples
  test/Fields/field_opt.jl
Labels: performance, tests, Performance monitoring :mag::rocket:
