Repository CliMA/ClimaCore.jl, pull requests merged in 2024-08, with the labels that each got.

#1913 Fixup get_struct unit tests
  test/DataLayouts/unit_struct.jl
Labels: unit tests

#1916 Add more fixes to get_struct unit tests
  test/DataLayouts/unit_struct.jl
Labels: unit tests

#1912 bump patch version to 14.11
  NEWS.md
  Project.toml
Labels: Release

#1917 Add thermo benchmark bandwidth script
  .buildkite/pipeline.yml
  benchmarks/scripts/benchmark_utils.jl
  benchmarks/scripts/thermo_bench_bw.jl
  src/Fields/fieldvector.jl
Labels: Performance monitoring :mag::rocket:

#1920 Remove multiple integer indexing in DataLayouts
  ext/cuda/limiters.jl
  ext/cuda/matrix_fields_single_field_solve.jl
  ext/cuda/remapping_distributed.jl
  lib/ClimaCorePlots/src/ClimaCorePlots.jl
  lib/ClimaCoreTempestRemap/src/netcdf.jl
  src/DataLayouts/DataLayouts.jl
  src/DataLayouts/fill.jl
  src/Fields/broadcast.jl
  src/Grids/Grids.jl
  src/Grids/finitedifference.jl
  src/Grids/spectralelement.jl
  src/Limiters/quasimonotone.jl
  src/MatrixFields/MatrixFields.jl
  src/MatrixFields/single_field_solver.jl
  src/Operators/Operators.jl
  src/Operators/finitedifference.jl
  src/Operators/numericalflux.jl
  src/Operators/spectralelement.jl
  src/RecursiveApply/RecursiveApply.jl
  src/Remapping/distributed_remapping.jl
  src/Topologies/Topologies.jl
  src/Topologies/dss.jl
  src/Topologies/dss_transform.jl
  test/DataLayouts/cuda.jl
  test/DataLayouts/data1d.jl
  test/DataLayouts/data1dx.jl
  test/DataLayouts/data2d.jl
  test/DataLayouts/data2dx.jl
  test/Limiters/limiter.jl
  test/Operators/finitedifference/convergence_column.jl
  test/Spaces/opt_spaces.jl
  test/Spaces/unit_spaces.jl
Labels: refactor

#1924 Update thermo benchmark script
  benchmarks/scripts/thermo_bench_bw.jl
Labels: Performance monitoring :mag::rocket:

#1926 Add offset benchmark
  .buildkite/pipeline.yml
  benchmarks/scripts/benchmark_offset.jl
Labels: Performance monitoring :mag::rocket:

#1930 add hyperbolic tangent stretching
  NEWS.md
  docs/src/api.md
  src/Meshes/interval.jl
  test/Meshes/interval.jl
Labels: enhancement, bugfix

#1935 New release for some libraries
  lib/ClimaCorePlots/Project.toml
  lib/ClimaCorePlots/src/ClimaCorePlots.jl
  lib/ClimaCoreTempestRemap/Project.toml
  lib/ClimaCoreTempestRemap/src/ClimaCoreTempestRemap.jl
  lib/ClimaCoreTempestRemap/src/netcdf.jl
  src/DataLayouts/DataLayouts.jl
Labels: Release

#1934 Reduce use of DataLayouts internals
  ext/cuda/cuda_utils.jl
  ext/cuda/data_layouts_copyto.jl
  ext/cuda/data_layouts_fill.jl
  ext/cuda/data_layouts_fused_copyto.jl
  ext/cuda/data_layouts_mapreduce.jl
  ext/cuda/limiters.jl
  ext/cuda/matrix_fields_multiple_field_solve.jl
  ext/cuda/matrix_fields_single_field_solve.jl
  ext/cuda/operators_finite_difference.jl
  ext/cuda/operators_integral.jl
  ext/cuda/operators_spectral_element.jl
  ext/cuda/operators_thomas_algorithm.jl
  ext/cuda/remapping_distributed.jl
  ext/cuda/remapping_interpolate_array.jl
  ext/cuda/topologies_dss.jl
  src/DataLayouts/DataLayouts.jl
  src/Topologies/dss.jl
  src/Topologies/dss_transform.jl
  test/DataLayouts/unit_copyto.jl
  test/DataLayouts/unit_fill.jl
  test/DataLayouts/unit_mapreduce.jl
  test/Operators/spectralelement/benchmark_utils.jl
  test/Spaces/distributed_cuda/ddss2.jl
  test/Spaces/distributed_cuda/ddss4.jl
  test/Spaces/opt_spaces.jl
  test/Spaces/unit_spaces.jl
Labels: refactor

#1937 Improve inference in grid constructors
  src/Grids/spectralelement.jl
  test/Spaces/opt_spaces.jl
Labels: Latency

#1944 Use internals less in DSS
  src/Topologies/dss.jl
Labels: refactor

#1946 Group data2array tests
  .buildkite/pipeline.yml
  test/DataLayouts/data0d.jl
  test/DataLayouts/data1dx.jl
  test/DataLayouts/data2d.jl
  test/DataLayouts/data2dx.jl
  test/DataLayouts/unit_data2array.jl
  test/runtests.jl
Labels: refactor

#1948 Remove more code duplication in DataLayouts
  src/DataLayouts/DataLayouts.jl
Labels: refactor

#1947 Fix integrals for broadcasts and update docstrings
  docs/make.jl
  src/Operators/integrals.jl
  test/Operators/integrals.jl
Labels: bugfix

#1954 Define == for same-typed fieldvectors
  src/Fields/fieldvector.jl
  test/Fields/unit_field.jl
  test/Fields/utils_field_multi_broadcast_fusion.jl
Labels: refactor

#1957 Reduce code duplication in DataLayouts
  src/DataLayouts/DataLayouts.jl
Labels: refactor

#1961 Refactor cubed sphere dss test
  .buildkite/pipeline.yml
  test/Spaces/ddss1.jl
  test/Spaces/ddss1_cs.jl
  test/runtests.jl
Labels: refactor, tests

#1965 Refactor and update benchmarks
  benchmarks/scripts/benchmark_offset.jl
  benchmarks/scripts/benchmark_utils.jl
  benchmarks/scripts/index_swapping.jl
  benchmarks/scripts/indexing_and_static_ndranges.jl
  benchmarks/scripts/thermo_bench.jl
  benchmarks/scripts/thermo_bench_bw.jl
  test/DataLayouts/benchmark_copyto.jl
Labels: refactor, Performance monitoring :mag::rocket:
