Repository CliMA/ClimaCore.jl, pull requests merged in 2024-06, with the labels that each got.

#1778 Fix dss type param
  Project.toml
  ext/cuda/topologies_dss.jl
  src/Spaces/dss.jl
  src/Topologies/dss.jl
  src/Topologies/dss_transform.jl
Labels: bugfix

#1779 Use Nv in VIJFH create_ghost_buffer type construction
  src/DataLayouts/DataLayouts.jl
  src/Topologies/dss_transform.jl
Labels: bugfix

#665 `DataLayouts` F Dimension Constructor Checks
  src/DataLayouts/DataLayouts.jl
  test/DataLayouts/data0d.jl
  test/DataLayouts/data1d.jl
  test/Spaces/ddss1.jl
Labels: bugfix

#1787 Fix dispatching for some cuda kernels
  .buildkite/pipeline.yml
  .github/workflows/docs.yml
  ext/ClimaCoreCUDAExt.jl
  ext/cuda/cuda_utils.jl
  ext/cuda/data_layouts.jl
  ext/cuda/fill.jl
  src/DataLayouts/DataLayouts.jl
  src/DataLayouts/broadcast.jl
  src/Fields/Fields.jl
  test/DataLayouts/benchmark_fill.jl
  test/DataLayouts/unit_fill.jl
  test/DataLayouts/unit_ndims.jl
  test/Fields/field_multi_broadcast_fusion.jl
  test/runtests.jl
Labels: bugfix

#1788 Add wrapper for FieldMatrix and FieldMatrixSolver
  NEWS.md
  Project.toml
  docs/src/matrix_fields.md
  src/MatrixFields/MatrixFields.jl
  src/MatrixFields/field_matrix_with_solver.jl
  test/MatrixFields/field_matrix_solvers.jl
Labels: enhancement

#1792 Bump patch for new release
  .buildkite/Manifest.toml
  .dev/Manifest.toml
  benchmarks/bickleyjet/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
Labels: Dependencies

#1793 Use ClimaComms allowscalar
  ext/cuda/matrix_fields_multiple_field_solve.jl
  src/MatrixFields/MatrixFields.jl
  src/MatrixFields/field2arrays.jl
  src/interface.jl
  test/DataLayouts/unit_fill.jl
  test/Fields/field.jl
  test/InputOutput/spectralelement2d.jl
  test/Limiters/limiter.jl
  test/Operators/hybrid/extruded_sphere_cuda.jl
  test/Operators/integrals.jl
  test/Operators/spectralelement/rectilinear_cuda.jl
  test/Spaces/ddss1.jl
  test/Spaces/distributed/ddss2.jl
  test/Spaces/distributed/ddss3.jl
  test/Spaces/distributed/ddss4.jl
  test/Spaces/distributed_cuda/ddss2.jl
  test/Spaces/distributed_cuda/ddss3.jl
  test/Spaces/extruded_cuda.jl
Labels: refactor

#1794 Reduce CUDA dependency in tests
  .buildkite/pipeline.yml
  test/Fields/field_multi_broadcast_fusion.jl
  test/InputOutput/spectralelement2d.jl
  test/Operators/hybrid/cuda.jl
  test/Operators/spectralelement/benchmark_ops.jl
  test/Operators/spectralelement/benchmark_utils.jl
  test/Operators/spectralelement/rectilinear.jl
  test/Operators/spectralelement/rectilinear_cuda.jl
  test/Spaces/distributed_cuda/ddss2.jl
  test/Spaces/distributed_cuda/ddss3.jl
  test/Spaces/distributed_cuda/ddss4.jl
  test/Spaces/distributed_cuda/ddss_ne32_cs.jl
  test/Spaces/distributed_cuda/space_construction.jl
  test/Spaces/extruded_cuda.jl
  test/runtests.jl
Labels: refactor

#1795 Decompose unit tests into unit, convergence, and simulation tests
  .buildkite/Project.toml
  .buildkite/pipeline.yml
  Project.toml
  test/Operators/finitedifference/convergence_advection_diffusion1d.jl
  test/Operators/hybrid/3d.jl
  test/Operators/hybrid/convergence_3d.jl
  test/Operators/hybrid/simulation_3d.jl
  test/Operators/hybrid/simulation_cuda.jl
  test/Operators/hybrid/unit_3d.jl
  test/Operators/hybrid/unit_cuda.jl
  test/Operators/hybrid/utils_3d.jl
  test/Operators/hybrid/utils_cuda.jl
  test/Operators/spectralelement/convergence_sphere_hyperdiffusion_vec.jl
  test/Operators/spectralelement/sphere_hyperdiffusion_vec.jl
  test/Operators/spectralelement/unit_diffusion2d.jl
  test/Operators/spectralelement/unit_sphere_hyperdiffusion.jl
  test/Operators/spectralelement/unit_sphere_hyperdiffusion_vec.jl
  test/Operators/spectralelement/utils_sphere_hyperdiffusion_vec.jl
  test/runtests.jl
Labels: refactor, tests

#1796 Partition correctness tests
  .buildkite/pipeline.yml
  test/Operators/finitedifference/benchmark_examples.jl
  test/Operators/finitedifference/linsolve.jl
  test/Operators/finitedifference/opt_examples.jl
  test/Operators/finitedifference/wfact.jl
  test/Operators/hybrid/convergence_2d.jl
  test/Operators/hybrid/unit_2d.jl
  test/Operators/hybrid/utils_2d.jl
  test/RecursiveApply/unit_recursive_apply.jl
  test/Utilities/unit_plushalf.jl
  test/aqua.jl
  test/runtests.jl
Labels: refactor, tests

#1802 Fix broken GPU dispatching
  .buildkite/pipeline.yml
  NEWS.md
  Project.toml
  ext/ClimaCoreCUDAExt.jl
  src/DataLayouts/DataLayouts.jl
  test/DataLayouts/unit_fill.jl
  test/DataLayouts/unit_ndims.jl
Labels: bugfix, GPU

#1798 Refactor terrain warp tests
  test/Spaces/terrain_warp.jl
Labels: refactor, tests

#1800 Iterate over unit tests, tabulate sorted timings
  .buildkite/pipeline.yml
  Project.toml
  test/MatrixFields/field_names.jl
  test/Spaces/ddss1.jl
  test/Spaces/distributed_cuda/ddss2.jl
  test/Spaces/distributed_cuda/ddss3.jl
  test/Spaces/distributed_cuda/ddss4.jl
  test/runtests.jl
  test/runtests_expensive.jl
  test/tabulated_tests.jl
Labels: refactor, tests

#1805 Define rebuild for DataF, and some type aliases
  ext/cuda/data_layouts.jl
  src/DataLayouts/DataLayouts.jl
  src/DataLayouts/broadcast.jl
  test/aqua.jl
Labels: refactor

#1809 Remove integral convergence tests from unit tests
  .buildkite/pipeline.yml
  test/Fields/convergence_field_integrals.jl
  test/Fields/unit_field.jl
  test/Spaces/distributed_cuda/ddss4.jl
Labels: refactor, tests

#1811 Add opt tests on space construction
  .buildkite/pipeline.yml
  test/Spaces/opt_spaces.jl
  test/Spaces/unit_spaces.jl
  test/runtests.jl
Labels: tests, Inference

#1810 Add test and improve inference of monotonic_check
  .buildkite/pipeline.yml
  src/Meshes/interval.jl
  test/Meshes/interval.jl
  test/Meshes/opt_meshes.jl
  test/Spaces/opt_spaces.jl
Labels: Inference, Allocations

#1813 Fix some inference failures in space construction
  src/Domains/Domains.jl
  src/Topologies/topology2d.jl
  test/Spaces/opt_spaces.jl
Labels: Inference

#1814 Specialize DataLayouts constructors
  src/DataLayouts/DataLayouts.jl
Labels: refactor

#1817 Add and fix DataLayouts `similar` opt test
  .buildkite/pipeline.yml
  src/DataLayouts/broadcast.jl
  src/Grids/finitedifference.jl
  src/Hypsography/Hypsography.jl
  test/DataLayouts/opt_similar.jl
Labels: tests, Inference

#1818 Add inference test and improve inference of `_SpectralElementGrid2D`
  src/Grids/spectralelement.jl
  test/Spaces/opt_spaces.jl
Labels: tests, Inference

#1822 Add thomas algorithm unit test to GHA
  .buildkite/pipeline.yml
  test/Operators/unit_thomas_algorithm.jl
  test/runtests.jl
Labels: tests

#1829 Add GPU job for stencil benchmarks
  .buildkite/pipeline.yml
  test/Operators/finitedifference/benchmark_column.jl
  test/Operators/finitedifference/benchmark_column_kernels.jl
  test/Operators/finitedifference/benchmark_column_utils.jl
Labels: Performance monitoring :mag::rocket:

#1832 Move rmul_with_projection to Geometry module
  .buildkite/pipeline.yml
  docs/make.jl
  docs/src/geometry.md
  docs/src/matrix_fields.md
  src/Geometry/Geometry.jl
  src/Geometry/rmul_with_projection.jl
  src/MatrixFields/MatrixFields.jl
  src/MatrixFields/band_matrix_row.jl
  src/MatrixFields/field_name_dict.jl
  src/MatrixFields/single_field_solver.jl
  test/Geometry/rmul_with_projection.jl
  test/runtests.jl
Labels: refactor

#1830 Assert symmetry of Cov/Contra-variant metric tensors
  lib/ClimaCoreTempestRemap/test/netcdf.jl
  src/Geometry/localgeometry.jl
  test/Fields/unit_field.jl
  test/Operators/finitedifference/convergence_advection_diffusion1d.jl
  test/Spaces/opt_spaces.jl
Labels: Defensive programming :crossed_swords:

#1835 Update dependencies
  .buildkite/Manifest.toml
  benchmarks/bickleyjet/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
Labels: Dependencies

#1836 Update and add cuda stencil benchmarks
  .buildkite/pipeline.yml
  test/Operators/finitedifference/benchmark_stencils.jl
  test/Operators/finitedifference/benchmark_stencils_array_kernels.jl
  test/Operators/finitedifference/benchmark_stencils_climacore_kernels.jl
  test/Operators/finitedifference/benchmark_stencils_utils.jl
  test/Operators/finitedifference/column_benchmark_profile.jl
Labels: Performance monitoring :mag::rocket:

#1840 Pass Nq and Nv throuh Val in copyto stencil
  ext/cuda/operators_finite_difference.jl
Labels: performance

#1843 Replace `_get_idx` w/ `CartesianIndices/LinearIndices`
  ext/ClimaCoreCUDAExt.jl
  ext/cuda/operators_finite_difference.jl
  ext/cuda/operators_integral.jl
  ext/cuda/operators_thomas_algorithm.jl
  ext/cuda/topologies_dss.jl
  src/Topologies/Topologies.jl
  src/Topologies/dss.jl
  src/Topologies/dss_transform.jl
  src/Utilities/Utilities.jl
  test/Spaces/opt_spaces.jl
Labels: refactor, tests

#1804 Add DataLayouts `copyto!` unit tests
  .buildkite/pipeline.yml
  ext/cuda/cuda_utils.jl
  ext/cuda/data_layouts.jl
  ext/cuda/data_layouts_copyto.jl
  ext/cuda/data_layouts_fill.jl
  src/DataLayouts/broadcast.jl
  src/Geometry/globalgeometry.jl
  test/DataLayouts/benchmark_fill.jl
  test/DataLayouts/unit_copyto.jl
Labels: tests, Coverage

#1844 Add mapreduce unit tests
  .buildkite/pipeline.yml
  test/DataLayouts/unit_mapreduce.jl
  test/runtests.jl
Labels: tests

#1845 Move mapreduce logic to DataLayouts layer
  ext/ClimaCoreCUDAExt.jl
  ext/cuda/data_layouts.jl
  ext/cuda/data_layouts_mapreduce.jl
  ext/cuda/fields.jl
  src/DataLayouts/broadcast.jl
  test/DataLayouts/unit_mapreduce.jl
  test/Spaces/distributed_cuda/ddss2.jl
Labels: refactor, tests

#1853 Break multiply_matrix_at_index into smaller functions
  src/MatrixFields/matrix_multiplication.jl
Labels: refactor

#1791 Remove CUDA from the test extras
  Project.toml
  test/MatrixFields/field_matrix_solvers.jl
  test/MatrixFields/matrix_field_test_utils.jl
  test/MatrixFields/operator_matrices.jl
Labels: Workflow :gear: :ocean:, Dependencies
