Repository CliMA/ClimaCore.jl, pull requests merged in 2024-01, with the labels that each got.

#1587 Remove truncated show for Fields
  src/Fields/Fields.jl
  test/Fields/field.jl
Labels: stack traces

#1507 Improve error messages for unknown types
  src/Fields/broadcast.jl
Labels: error message

#1598 Fix allocations for operator matrices with mixed boundary conditions
  src/MatrixFields/operator_matrices.jl
Labels: bugfix
