Repository CliMA/ClimaCore.jl, pull requests merged in 2025-01, with the labels that each got.

#2120 Move in-kernel specific adapt functions to cuda ext
  ext/ClimaCoreCUDAExt.jl
  ext/cuda/adapt.jl
  src/Grids/extruded.jl
  src/Grids/finitedifference.jl
  src/Grids/spectralelement.jl
  src/Spaces/pointspace.jl
  src/Topologies/interval.jl
  test/Spaces/unit_spaces.jl
Labels: refactor, GPU

#2121 Update dependencies
  .buildkite/Manifest.toml
  .dev/Manifest.toml
  benchmarks/bickleyjet/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
Labels: Dependencies

#2127 Fix plotting for columns from extruded FD fields
  lib/ClimaCorePlots/src/ClimaCorePlots.jl
  lib/ClimaCorePlots/test/runtests.jl
Labels: bugfix, ClimaCorePlots

#2122 Add high resolution space construction tests
  .buildkite/pipeline.yml
  test/Spaces/high_resolution_space.jl
  test/Spaces/unit_high_resolution_space.jl
Labels: tests, GPU

#2139 Add missing `post_op_callback` calls
  NEWS.md
  docs/src/debugging.md
  src/CommonSpaces/CommonSpaces.jl
  src/Fields/fieldvector.jl
Labels: bugfix, Debugging

#2141 Update NEWS, and bump patch version
  NEWS.md
  Project.toml
Labels: Release

#2143 Add data2array support for DataF layouts
  NEWS.md
  src/DataLayouts/DataLayouts.jl
  test/DataLayouts/unit_data2array.jl
Labels: feature, Purely single column support

#2144 Update to latest LazyBroadcast
  .buildkite/Manifest.toml
  Project.toml
  benchmarks/bickleyjet/Manifest.toml
  benchmarks/scripts/benchmark_utils.jl
  benchmarks/scripts/index_swapping.jl
  benchmarks/scripts/indexing_and_static_ndranges.jl
  lib/ClimaCoreMakie/examples/Manifest.toml
  src/ClimaCore.jl
  src/lazy_broadcast.jl
  test/DataLayouts/unit_has_uniform_datalayouts.jl
  test/DataLayouts/unit_linear_indexing.jl
  test/DataLayouts/unit_non_extruded_broadcast.jl
  test/MatrixFields/matrix_field_test_utils.jl
  test/MatrixFields/operator_matrices.jl
  test/Spaces/opt_spaces.jl
Labels: Dependencies

#2148 Fix getidx for GradientC2F with SetValue bcs
  src/Operators/finitedifference.jl
  test/Operators/finitedifference/unit_column.jl
Labels: bugfix

#2147 Add do-syntax support for HDF5Reader/Writer
  NEWS.md
  examples/sphere/shallow_water_cuda.jl
  lib/ClimaCoreMakie/examples/file.jl
  lib/ClimaCoreTempestRemap/test/mpi_tests/online_remap.jl
  src/InputOutput/readers.jl
  src/InputOutput/writers.jl
  test/InputOutput/unit_finitedifference.jl
  test/InputOutput/unit_hdf5.jl
  test/InputOutput/unit_hybrid2dbox.jl
  test/InputOutput/unit_hybrid2dbox_stretched.jl
  test/InputOutput/unit_hybrid2dbox_topography.jl
  test/InputOutput/unit_hybrid3dbox.jl
  test/InputOutput/unit_hybrid3dcubedsphere.jl
  test/InputOutput/unit_hybrid3dcubedsphere_topography.jl
  test/InputOutput/unit_spectralelement2d.jl
Labels: feature

#2152 Improve limiter debug info, update deformation flow example and buffers
  examples/hybrid/sphere/deformation_flow.jl
  ext/ClimaCoreCUDAExt.jl
  ext/cuda/adapt.jl
  ext/cuda/limiters.jl
  src/Limiters/quasimonotone.jl
Labels: CI

#2161 Fix reinstantiation of spectral broadcasted
  src/Operators/spectralelement.jl
  test/Operators/unit_reinstantiate_bc.jl
  test/runtests.jl
Labels: bugfix

#2163 Define `to_device` and `to_cpu`
  NEWS.md
  docs/make.jl
  docs/src/api.md
  docs/src/faq.md
  src/ClimaCore.jl
  src/to_device.jl
  test/Fields/unit_field.jl
Labels: feature, GPU

#2164 Bump patch version, update dependencies
  .buildkite/Manifest.toml
  .dev/Manifest.toml
  Project.toml
  benchmarks/bickleyjet/Manifest.toml
  lib/ClimaCoreMakie/examples/Manifest.toml
Labels: Release, Dependencies

#2136 Clarify DSS weights and fix DSS buffer bug
  ext/cuda/topologies_dss.jl
  src/Fields/Fields.jl
  src/Grids/Grids.jl
  src/Grids/extruded.jl
  src/Grids/level.jl
  src/Grids/spectralelement.jl
  src/Quadratures/Quadratures.jl
  src/Spaces/Spaces.jl
  src/Spaces/dss.jl
  src/Spaces/extruded.jl
  src/Spaces/spectralelement.jl
  src/Topologies/dss.jl
  src/Topologies/dss_transform.jl
  test/Spaces/unit_dss.jl
  test/Spaces/unit_spaces.jl
Labels: bugfix
